### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by axelhzf** [connyay/openshift-iojs#1]
I'm having problems running websockets with this cartridge. Do yo know if its possible?

**Comment by connyay** [comment]
Hey @axelhzf,

I haven't personally tried it so I'm not sure. But I don't see why not. Did [this commit](https://github.com/axelhzf/openshift-iojs/commit/e254022f1222beb9907713ba12f8f08acf507ea1) fix it?

**Comment by axelhzf** [comment]
I have tried several things and I thought [this commit](https://github.com/axelhzf/openshift-iojs/commit/e254022f1222beb9907713ba12f8f08acf507ea1) was neccesary, but actually don't. The problem was my application.

I have upload a simple application to test it

```
rhc create-app websocket http://tinyurl.com/OpenShiftIOJS --from-code https://github.com/axelhzf/simple-socket-openshift-iojs.git
```
