### ISSUE TITLE
Possible to upgrade to newer version of iojs?

### ISSUE THREAD

**Issue by probins** [connyay/openshift-iojs#6]
More of a question than an issue. Readme mentions ramr/nodejs-custom-version-openshift which provides a technique for doing this with nodejs. Does this also work with this cartridge? I might be interested in upgrading to 3.0.0 if so.

**Comment by connyay** [comment]
Currently - no. io.js was moving very quickly when I created this cartridge and wanted a bit more fine control over which version was used. It is starting to slow down / stabilize so I might move to resolving versions on the gears in the very near future.

**Comment by probins** [comment]
ok. I'll leave this open for the moment as a reminder. Feel free to close if you prefer.

**Comment by whitfin** [comment]
@connyay seeing as Node.js v4 is about to go live (which is the convergence of io.js and Node.js), any chance of bumping to v4? 

Ref: https://github.com/nodejs/node/issues/2522

**Comment by connyay** [comment]
@iwhitfield Once v4 is out of RC I will bump. I have been mashing F5 so don't you worry :grin:

**Comment by connyay** [comment]
Decided to split v4 to a new repo can be found [here](https://github.com/connyay/openshift-node4).

**Comment by connyay** [comment]
@iwhitfield if you decide to try out node4 pay careful attention to [env variables](https://github.com/connyay/openshift-node4/blob/master/template/app.js#L4-L5)

**Comment by connyay** [comment]
Node.js v4 is running here: http://node4-connyay.rhcloud.com/

**Comment by probins** [comment]
there's still a need for easy version upgrade with the new node4 as well.
